### ISSUE TITLE
Publish on Python Package Index?

### ISSUE THREAD

**Issue by noelleleigh** [graphql-python/graphene-federation#5]
Is this package listed on [pypi.org](https://pypi.org/)? If so, can a link to its listing be added to README.md?

**Comment by erikwrede** [comment]
release on PyPi is WIP; except more news by the end of the week! 🙂 
you can already find the older releases from preply over at pypi; these don't support graphene 3/federation 2 yet.I recently got their release token and will set everything up for the v3 releases very soon!

**Comment by erikwrede** [comment]
`v3.0.1` is released on PyPi, you can check it out there!
I'll try to add the missing `v3.0.0` tag later.
